site_name: Some mur mur things
site_url: https://wu0up.github.io/blog_material/
nav:
  - polaris - A Safety-focused LLM Constellation Architecture for Healthcare : ./20240829.md
  - A Survey on Large Language Model based Autonomous Agents: ./20240902.md
theme:
  name: material


copyright: |
  &copy; 2024 <a href="https://github.com/wu0up"  target="_blank" rel="noopener">Vivian Ou</a>